name: Dispatch sag-playground CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  trigger-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger sag-playground CI
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.REPO_DISPATCH_PAT }}
          script: |
            const response = await github.repos.createDispatchEvent({
              owner: 'sag-lang-project',
              repo: 'sag-playground',
              event_type: 'sag-main-update',
            });
            console.log(response);
